import = ["~/.config/alacritty/themes/catppuccin.toml"]
live_config_reload = true

[window]
dynamic_padding = true
opacity = 0.95
blur = true

[font]
normal = { family = "Maple Mono NF" }
size = 11.00
