[".config/nvim"]
    type = "archive"
    url = "https://github.com/NvChad/NvChad/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/init.lua", "*/.stylua.toml", "*/lua/**"]
["AppData/Local/nvim"]
    type = "archive"
    url = "https://github.com/NvChad/NvChad/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/init.lua", "*/.stylua.toml", "*/lua/**"]
