#!/usr/bin/env bash
# shellcheck disable=SC1090,SC1091

. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/env.sh"

BASH_ENV=

. "${XDG_CONFIG_HOME:-$HOME/.config}/shell/login.sh"

if [ "$PS1" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/shell/interactive.bash"
fi
