import = ["~/.config/alacritty/themes/catppuccin.toml"]
live_config_reload = true

[window]
dynamic_padding = true
opacity = 0.9
blur = true

[font]
normal = { family = "FiraCode Nerd Font" }
size = 11.00
