[include]


[misc]
pre_sudo = true
sudo_command = "sudo"
disable = ["gcloud"]
assume_yes = true
no_retry = true
run_in_tmux = true
tmux_session_mode = "attach_if_not_in_session"
cleanup = true

[brew]
greedy_cask = true
