#! /bin/sh

## clear rules
bspc rule -r "*"

borderbase=2
monocle_padding=-$borderbase
padding=$borderbase

#### Set Coloring ####
unfocused="#1d1f21"
focused="#81a2be"
select="#b294bb"
urgent="#cc6666"

# You need to change this if you have multiple monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

###---Monitor And Desktop Settings----###
bspc config border_width         2
bspc config window_gap           12
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false

###---Global Settings---###
bspc config automatic_scheme      alternate
bspc config initial_polarity      second_child
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
bspc config click_to_focus        none

bspc config focus_follows_pointer      true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

#### BSPWM coloring ####
bspc config normal_border_color    $unfocused
bspc config active_border_color    $unfocused
bspc config focused_border_color   $focused
bspc config presel_feedback_color  $select
bspc config urgent_border_color    $urgent

###---Rules---###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a feh state=floating
bspc rule -a krita state=floating
bspc rule -a blender state=floating
bspc rule -a obs state=floating
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled
bspc rule -a Zathura state=tiled

###---Autostart---###
polylaunch
