#! /bin/sh

## Get colors from .Xresources -------------------------------#
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors
xrdb ~/.Xresources

## Configurations -------------------------------#
border=2
gap=10

# #### Set Coloring ####
focused="$BLUE"
normal="$BACKGROUND"
active="$MAGENTA"
select="$GREEN"
urgent="$RED"

###---Monitor And Desktop Settings----###
bspc config window_gap           "$gap"
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        false

###---Global Settings---###
bspc config automatic_scheme      alternate
bspc config initial_polarity      second_child
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side
bspc config pointer_action3       resize_corner
bspc config click_to_focus        none

bspc config focus_follows_pointer      true
#bspc config pointer_follows_focus true  #Some keybindings automatically enable and disable this setting
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

#### BSPWM coloring ####
##Color settings
bspc config border_width           "$border"
bspc config normal_border_color    "$normal"
bspc config active_border_color    "$active"
bspc config focused_border_color   "$focused"
bspc config presel_feedback_color  "$select"
bspc config urgent_border_color    "$urgent"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor -d i ii iii iv v vi vii viii ix x
#bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d • • • • • • • • • •
#bspc monitor -d I II III IV V VI

###This creates and names desktops for multiple monitors.
workspaces_multimonitor &

## Window rules -------------------------------#

# remove all rules first
bspc rule -r "*"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a feh state=floating
bspc rule -a krita state=floating
bspc rule -a blender state=floating
bspc rule -a obs state=floating
bspc rule -a sxiv state=pseudo_tiled
bspc rule -a mpv state=pseudo_tiled
bspc rule -a Zathura state=tiled

## Autostart -------------------------------#

# Kill if already running
# killall -9 sxhkd xsettingsd dunst mpd

polylaunch

# Lauch keybindings daemon
# sxhkd &
