#!/usr/bin/env bash

# rofi_command="rofi -theme themes/powermenu.rasi"
rofi_command="rofi"

### Options ###
power_off=" shutdown"
reboot=" reboot"
lock=" lock"
suspend="鈴 sleep"
log_out=" logout"

# Variable passed to rofi
options="$power_off\n$reboot\n$lock\n$suspend\n$log_out"

case "$(echo -e "$options" | $rofi_command -dmenu -selected-row 2)" in
    $power_off)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        mpc -q pause
        zzz
        ;;
    $suspend)
        mpc -q pause
        zzz -f
        ;;
    $log_out)
        bspc quit
        ;;
esac
