#!/usr/bin/env sh
# Simple script that uses maim to take a screenshot

outputdir="$HOME/Pictures/screenshots"
output="$outputdir/"$(date '+%F_%H%M%S').png""

if [ ! -d "$outputdir" ]; then
    mkdir -p "$outputdir"
fi

menu () {
    echo "" | rofi -dmenu -p "How Long?" | xargs -I _ sleep "_"
}

imgur () {
    xclip -selection clipboard -t image/png -i "$output" && imgurbash2 "$output"
}

case "$1" in
    "full")
        maim -u -m 9 "$output" && xclip -se c -t image/png -i "$output" && imgurbash2 "$output" || exit
        ;;

    "select")
        if pidof picom > /dev/null 2>&1; then
            maim -u -m 9 -c 1,0,1.5,0.2 -l -s "$output" && xclip -se c -t image/png -i "$output" && imgurbash2 "$output" || exit
        else
            maim -u -m 9 -c 1,0,1.5,0.2 -s "$output" && xclip -se c -t image/png -i "$output" && imgurbash2 "$output" || exit
        fi
        ;;

    "fulltime")
        menu && maim -m 9 "$output" || exit
        menu && maim -m 9 "$output" || exit
        ;;

    "selecttime")
        if pidof picom > /dev/null 2>&1; then
            menu && maim -m 9 -c 1,0,1.5,0.2 -l -s "$output" || exit
        else
            menu && maim -m 9 -c 1,0,1.5,0.2 -s "$output" || exit
        fi
        ;;

esac

notify-send "Maim" "Screenshot Taken"
