#!/usr/bin/env sh
# Preview script built for use with lf and fzf
LINES=30
case "$1" in
    *.png|*.jpg|*.jpeg|*.gif) chafa --fill=block --symbols=block -c 256 -s 80x "$1";;
    *.mkv|*.mp4|*.flv|*.webm) mediainfo "$1";;
    *.md) glow -s dark "$1";;
    *.pdf) pdftotext "$1" -;;
    *.zip) zipinfo "$1";;
    *.tar.gz) tar -ztvf "$1";;
    *.tar.bz2) tar -jtvf "$1";;
    *.tar) tar -tvf "$1";;
    *.rar) unrar l "$1";;
    *.7z) 7z l "$1";;
    *) highlight "$1" -O ansi --force;;
esac
