#!/usr/bin/env sh

# ====== Variables =============================

padding=12
gap=06

# set names for spaces
yabai -m space 1 --label I
yabai -m space 2 --label II
yabai -m space 3 --label III
yabai -m space 4 --label IV
yabai -m space 5 --label V
yabai -m space 6 --label VI
yabai -m space 7 --label VII
yabai -m space 8 --label VIII
yabai -m space 9 --label IX
yabai -m space 10 --label X

# ====== Tiling settings =======================

yabai -m config layout                       bsp

yabai -m config top_padding                  "$padding"
yabai -m config bottom_padding               "$padding"
yabai -m config left_padding                 "$padding"
yabai -m config right_padding                "$padding"
yabai -m config window_gap                   "$gap"

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off

yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# specific space settings
# yabai -m config --space 7 layout	float

# ====== List of rules =========================

yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="The Unarchiver" app="^The Unarchiver$" manage=off
yabai -m rule --add label="Transmission" app="^Transmission$" manage=off
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" manage=off
yabai -m rule --add label="Digital Color Meter" app="^Digital Colou?r Meter$" sticky=on
yabai -m rule --add label="Microsoft AutoUpdate" app="^Microsoft AutoUpdate$" manage=off
yabai -m rule --add label="Alfred Preferences" app="^Alfred Preferences$" manage=off
yabai -m rule --add label="Bartender Preferences" app="^Bartender 3$" manage=off
yabai -m rule --add label="BetterTouchTool" app="^BetterTouchTool$" manage=off
yabai -m rule --add label="Emacs" app="^Emacs$" manage=on

# ====== List of signals =======================

# # refresh my Übersicht bar when the space changes
# yabai -m signal --add event=space_changed \
#     action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"spaces-widget\"'"

# focus window under cursor when a window is destroyed
yabai -m signal --add event=window_destroyed \
    action="yabai -m query --windows --window &> /dev/null \
    || yabai -m window --focus mouse"

# focus window under cursor when an application is terminated
yabai -m signal --add event=application_terminated \
    action="yabai -m query --windows --window &> /dev/null \
    || yabai -m window --focus mouse"

# kill limelight when an application is activated
# yabai -m signal --add event=application_activated \
#     action="pkill -SIGUSR1 limelight &> /dev/null"
#
yabai -m signal --add event=space_changed action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"
yabai -m signal --add event=display_added action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"
yabai -m signal --add event=display_removed action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"
yabai -m signal --add event=display_changed action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"
yabai -m signal --add event=display_moved action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"

echo "yabai configuration loaded.."
