#!/usr/bin/env sh
# Simple script to generate a script file in my scripts directory

file=$HOME/.local/bin/$1

if [ -d "$HOME/.local/bin" ]; then
  if [ -e "$HOME/.local/bin/$1" ]; then
    $EDITOR "$file"
  else
    echo "#!/usr/bin/env sh" >> "$file"
    chmod +x "$file"
    $EDITOR "$file"
  fi
fi
