#!/usr/bin/env bash
# Launches an instance of polybar

# Use predefined launch script from premade themes
if [ -x "${XDG_CONFIG_HOME:-$HOME/.config}/polybar/launch.sh" ]; then
  "${XDG_CONFIG_HOME:-$HOME/.config}/polybar/launch.sh"

else
  # Terminate already running bar instances
  killall -q polybar

  # Wait until the processes have been shut down
  while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

  # Launch bar on every monitor
  for m in $(polybar -m | awk -F ':' '{print $1}'); do
      MONITOR=$m polybar main -r -c ~/.config/polybar/config.ini &
  done

fi
